/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.webtv;

import java.io.File;

import com.webtv.service.FileUploader;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }

    @Bean
    CommandLineRunner createUploadDir() {
        return (args) -> {
            new File(FileUploader.UPLOADS_DIR).mkdirs();
        };
    }
}
