package com.webtv.controller;

import javax.validation.Valid;

import com.webtv.commons.GoogleCredential;
import com.webtv.commons.ResponseModel;
import com.webtv.entity.VideoYoutube;
import com.webtv.service.endpoints.ShareService;
import com.webtv.service.youtube.GoogleAuth;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;

@Api(description = "API Endpoints for Google authentification.")
@RestController
@RequestMapping("api/v1")
public class GoogleAuthController {

    @Autowired
    private GoogleAuth auth;

    @Autowired
    private ShareService shareService;

    @ApiOperation("AuthorizeUrl. Get the url for attempting user to accept the request. The client must show the url generated by this endpoint before first uploading a video.")
    @GetMapping("auth/googleauthorize-url")
    ResponseModel<String> authorizeUrl() {
        return ResponseModel.success(auth.authorizeUrl().build());
    }

    @ApiOperation("ShareVideo. Share the video using youtube.")
    @PostMapping("google/share-youtube/{videoId:[0-9]+}")
    ResponseModel<VideoYoutube> shareYoutube(@Valid VideoYoutube video, BindingResult bResult, @PathVariable("videoId") Long videoId) {
        return shareService.share(video, bResult, videoId);
    }

    @ApiOperation("CallbackUrl. Save the google auth code or load an authenticated user. The 'code' paramater is a param callback from google.")
    @GetMapping("auth/google/authorized-url")
    ResponseModel<GoogleCredential> onAuthorizeUrl(@RequestParam(name = "code", required = false) String code) {
        if(code != null) {
            return ResponseModel.success(GoogleCredential.of(auth.forNewCode(code)));
        }
        return ResponseModel.success(GoogleCredential.of(auth.authorize("fanabned@gmail.com")));
    }
}